### ISSUE TITLE
Links offset from text.

### ISSUE THREAD

**Issue by ccfcs-ttu** [Tizra/Tizra-Customer-Tracker#444]
We have run into an issue where none of the actual link boxes line up with the text for said link. The link box, that you can click on and open the file, is actually 2-3 inches below the text. Republishing the documents from the Collection>Documents page for the entire course does not fix the issue. Going into each individual document and re-publishing does fix the issue. This also changes the way the page initially loads. The pages are zoomed out to show the entire page without having to scroll. I believe something about this change may be what is causing issues in the documents that have not been re-published.

Example of issue: [http://ccfcs.tizrapublisher.com/2017_id_space_planning/2]
After re-publishing: [http://ccfcs.tizrapublisher.com/2017_id_leadership/2]

Edit:
Customers say this started yesterday.

This also only seems to be an issue when using Firefox.

**Comment by adane** [comment]
Hi Derrick--

We think the problem is fixed now.  Can you take another look?  Be sure to do a force refresh before testing.

Thank you.

Abe

**Comment by ccfcs-ttu** [comment]
Abe,

I’ve cleared my entire history and done multiple hard refreshes. I have looked at multiple documents in multiple courses, and they all still have the issue.

Derrick

**Comment by daviddurand** [comment]
Can you let us know what version you're using... maybe there's a dependency there, as we were not seeing it in Firefox....

**Comment by daviddurand** [comment]
Found the CSS issue for Firefox. It's fixed now. Thanks for the report!

**Comment by ccfcs-ttu** [comment]
I'm using version 57.0.4 and everything seems to be working properly now. Thank you!
